### ISSUE TITLE
Feature Request: iOS like sliding when a new sticky overtakes the previous one

### ISSUE THREAD

**Issue by switz** [yahoo/react-stickynode#125]
When you scroll on an iOS list view, the next sticky section header will actually push up the current sticky header rather than just sliding on top of it. This is subtle but is actually really clean and pleasant UX.

Here's a video showing what I mean. Look at the "Featured" and "Favorite" sticky headers: https://streamable.com/vuk5z

I'm happy to send a PR if this is something you guys are interested in having.

**Comment by LeeIakokka** [comment]
How would one actually accopmlish that? I'd be interested in having such option. +1

**Comment by redonkulus** [comment]
@switz If you still want this, you can open a PR and we can review it. Closing for now.

**Comment by kevinmmmcs** [comment]
Hmmm, I'm not sure how it would best be implemented but FWIW this is by no means an iOS-specific behavior: this is how normal `position: sticky` elements behave when their containing block is something other than the viewport, as long as the sticky elements in question have different containing blocks that are children of the same scrolling container.  (...I hope I explained that accurately.)  See https://jsfiddle.net/4tmcLjq3/3/

Unfortunately since `react-stickynode` avoids the pitfalls of `position: sticky` by ~faking it using `position: fixed` I'm not sure how feasible this would be to implement without changing a bunch of stuff -- a fixed element's containing block is _always_ the viewport.  But maybe something kinda like this can be accomplished through a clever combination of `top`/`bottomBoundary` selectors, styles targeted to `releasedClass`, and the right DOM structure?  I'm not deeply familiar with `Sticky`'s internals yet, but I can try to noodle on it some more 😅
