### ISSUE TITLE
Doesn't work on scrolling containers other than <body>

### ISSUE THREAD

**Issue by mmmeff** [yahoo/react-stickynode#26]

**Comment by mmmeff** [comment]
After some light investigation, I've determined that the issue lies with the usage of the `subscribe-ui-events` library, or rather a limitation of that library.

**Comment by hankhsiao** [comment]
You mean you use it in a DIV with overflow:scroll?

**Comment by mmmeff** [comment]
Exactly

**Comment by origsun** [comment]
+1

checkout [subscribe-ui-events/src/mainEventConnectors.js](https://github.com/yahoo/subscribe-ui-event/blob/af423edad48cc9cee13b732f59eaa9f1dc8bc0ea/src/mainEventConnectors.js) 
`subscribe-ui-events` only listens to scroll events on `window`.

When you set 
- `html, body` to `{ overflow: hidden}` 
- `#container` to `{ height: 100%; width: 100%; position: absolute; overflow: auto}`,

scrolling inside the container does not trigger scroll events on window.

**Comment by juhaelee** [comment]
Can [subscribe v1.0.7](https://github.com/yahoo/subscribe-ui-event/releases/tag/v1.0.7) listen to scroll events on specific targets? @hankhsiao

**Comment by juhaelee** [comment]
@mmmeff Have you been able to find a sticky solution that works with non-body elements?

**Comment by mmmeff** [comment]
@juhaelee Nope

**Comment by mmmeff** [comment]
@juhaelee taking a stab at this right now, look for a PR later today @hankhsiao @src-code

**Comment by hankhsiao** [comment]
Sticky is not designed in this case. It needs fundamental changes.

There are some fundamental differences. For example, to handle sticking to the viewport with high performance, we use `position: fixed` instead of using `position: absolute` and changing `top` all the time when scrolling (I know some sticky components do that). In this case, `fixed` won't be correct in a scrollable DIV.

Every component has its fundamental assumptions where we implemented based on. Those assumptions are also limitations. I am afraid this sticky can do what you want. I suggest you to find another simpler sticky which does similar thing I described above.

**Comment by mmmeff** [comment]
@hankhsiao You're right. Ditching my fork for the time being - only had a long lunch break's worth of time to work on this and quickly ran up against that wall. Bummer!

**Comment by danielberndt** [comment]
In case you're curious what a solution could look like, have a look at this:
https://github.com/danielberndt/react-sticky-box/blob/master/src/index.js

This component is certainly not as feature rich as this one here, but at least it's supposed to be working in all types of scroll containers. And it's not that much more additional code. So feel free to take whatever parts are helpful to you :)

**Comment by chrisvxd** [comment]
Thanks @danielberndt- using your library now! Works well 👍
