### ISSUE TITLE
Add react 16 compatibility 

### ISSUE THREAD

**Issue by HashemKhalifa** [yahoo/react-stickynode#90]
Kindly add react-addons-shallow-compare version 16 as well, 
or I might create a pull request!

**Comment by redonkulus** [comment]
Looks like a React 16 version has not been published, https://www.npmjs.com/package/react-addons-shallow-compare, are you seeing a warning somewhere?

**Comment by setevik** [comment]
According to [upgrade guide](https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#discontinuing-support-for-react-addons), this add-on supposed to be replaced by PureComponent
This PR seems relevant: https://github.com/yahoo/react-stickynode/pull/87

**Comment by computapars** [comment]
Will this package work with React 16?

**Comment by MilllerTime** [comment]
@computapars Working just fine with React 16 here.

**Comment by HashemKhalifa** [comment]
@MilllerTime yes works perfectly fine

**Comment by MilllerTime** [comment]
It appears there is a potential compile error when using React 16. react-addons-shallow-compare seems to expect the folder structure of React 15. After refactoring some dependencies recently, I started getting a compile error from webpack because it couldn't resolve a `react/lib/...` import in react-addons-shallow-compare. My guess is I still has React 15 lurking somewhere before, and now it's gone.

After installing a forked version of this repo instead and incorporating a slightly tweaked version of PR #87, everything is working great! That PR is necessary for proper React 16 support.

**Comment by Keksike** [comment]
If someone ends up here and is looking to get a working solution with React >=16, try this package, worked brilliantly for me: https://www.npmjs.com/package/react-sticky-el

**Comment by roderickhsiao** [comment]
This is addressed in #123
